GROUP_LABEL="OBS Studio (capture vidéo)"
GROUP_PACMAN=()
GROUP_AUR=(obs-vkcapture-git)
GROUP_FLATPAK=(com.obsproject.Studio)
GROUP_POST_INSTALL_MSG="Pour la capture Vulkan, ajouter OBS_VKCAPTURE=1 dans ~/.config/environment.d/envvars.conf ou dans les arguments du jeu sur steam"